# Generated by Django 4.2 on 2024-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kind',
            field=models.CharField(choices=[('user', 'user'), ('company', 'company')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='time_work',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
