# Generated by Django 4.2 on 2024-04-27 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_chat_user_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
