# Generated by Django 4.2 on 2024-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_comment_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_using',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='context',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.URLField(blank=True),
        ),
    ]
